### ISSUE TITLE
UI Designer not working properly -  "Couldn't find corresponding file."

### ISSUE THREAD

**Issue by slidebend** [nodea-software/nodea#1]
Hello team,
I have created an account on demo env, created an application manually and then executed following instructions:
```
add entity Photo
add field Capture with type image
create entity Category
add field Nom
set field Nom required
set icon tag
select entity Photo
set icon camera
add field Category related to Category using Nom
add component status with name Statut
add component address with name Address
```
Everything works fine until I do the following:
- Move "status" field in the UI Designer
- Check "Apply to all"
- Click "Save" button

I then encounter a toastr error that says: "Couldn't find corresponding file."
Fields has moved (I can see it when I refresh page) but nothing appears in logs 
Any idea of what happens ?
Thank you

**Comment by Syno0** [comment]
Rework of UI Designer in order to fix multiple issues at the same time
https://github.com/nodea-software/nodea/commit/a326fd68ae7b9e7106fe2d5ca9936392ab1f81f0

**Comment by Syno0** [comment]
Available on https://test.nodea.studio

**Comment by slidebend** [comment]
Fixed
