### ISSUE TITLE
Code source edition seems to be limited

### ISSUE THREAD

**Issue by annelvk** [nodea-software/nodea#10]
Hi,

I have just set up my account tonight and tried my first application called "neufmai".

Unfortunately, I'm not able to find the code of the Personne entity I've just added on my application.
I am looking for the directory "app / views / e_personne " in the source code editor.
But this is not available.
I have to disconnect and reconnect. This is not so easy to understand.

Coukld you fix this please ?

Anne.

**Comment by Syno0** [comment]
https://github.com/nodea-software/nodea/commit/eb1ee3779b937106eea1fae4b8cb2a253de32c38

**Comment by Syno0** [comment]
Available on https://test.nodea.studio

**Comment by annelvk** [comment]
I've just done the same test and now this is ok. Thanks.
