### ISSUE TITLE
Translation is broken after using the UI designer

### ISSUE THREAD

**Issue by Alex-Ljeune** [nodea-software/nodea#11]
Hello team, 

I just moved a field in the UI designer and the title of this field and the next one didnt support translation anymore. See : 
![Capture d’écran du 2021-05-11 16-49-19](https://user-images.githubusercontent.com/70142940/117836293-d8ea8580-b278-11eb-913d-590459d0044f.png)

It seems to be quite random, when I use the UI designer some fields breaks but not necessarily the ones I moved.
Any ideas ?

**Comment by Syno0** [comment]
Rework of UI Designer in order to fix multiple issues at the same time
https://github.com/nodea-software/nodea/commit/a326fd68ae7b9e7106fe2d5ca9936392ab1f81f0

**Comment by Syno0** [comment]
Available on https://test.nodea.studio

**Comment by Alex-Ljeune** [comment]
Perfect, thank you :)
