### ISSUE TITLE
Field "Format Pair" in document template goes back to "Dust template to PDF document" after update

### ISSUE THREAD

**Issue by egazarian** [nodea-software/nodea#15]
Create a _document template_ with the field **Format Pair** set to _Word template to word document_. After that update it by changing some fields and save. The field **Format Pair** goes back to **Dust template to PDF document** automatically.

**Comment by EoiFirst** [comment]
A fix will be available in version 3.0.2

**Comment by Syno0** [comment]
Test available on https://test.nodea.studio/
