### ISSUE TITLE
document_template not filtered by entity

### ISSUE THREAD

**Issue by egazarian** [nodea-software/nodea#16]
On the document template tab of an entity, the select field is not filtered by the entity. All the documents templates are displayed.

**Comment by Syno0** [comment]
Will be fixed in 3.0.2

See https://github.com/nodea-software/nodea/commit/8f7398ff4c1684ea3ec14d368771bc4a334c2f89

**Comment by Syno0** [comment]
Test available on https://test.nodea.studio/
