### ISSUE TITLE
Hooks for widget

### ISSUE THREAD

**Issue by Alex-Ljeune** [nodea-software/nodea#17]
Hello team, it would be nice to have hooks to custom the widgets !

**Comment by Syno0** [comment]
start and beforeSend hooks will be added in 3.0.2

See https://github.com/nodea-software/nodea/commit/daba34db3dac9b96807646f153d12f5cb68bb050

**Comment by Syno0** [comment]
Test available on https://test.nodea.studio/

**Comment by Alex-Ljeune** [comment]
Thanks !
