### ISSUE TITLE
It's possible to create a document template without setting an entity

### ISSUE THREAD

**Issue by egazarian** [nodea-software/nodea#18]
It's possible to create a document template without selecting an entity in the creation form, but the field is normally required.

**Comment by Syno0** [comment]
Will be fixed in 3.0.2

See commit: https://github.com/nodea-software/nodea/commit/4b947fc355b4662ea4c50251f4f483c129b0704f

**Comment by Syno0** [comment]
Test available on https://test.nodea.studio/
