### ISSUE TITLE
Redirect after login

### ISSUE THREAD

**Issue by egazarian** [nodea-software/nodea#19]
Redirect after login is not working. For example, `/login?r=/entity/update_form?id=5` don't redirect to the update_form.

**Comment by Syno0** [comment]
Problem solved in 3.0.2.

For your current project you just have to replace
`<form action="/login" method="post">`
with
`<form action="/login?r={redirect}" method="post">`

in your **/app/views/login/login.dust** file.

**Comment by Syno0** [comment]
Test available on https://test.nodea.studio/
