### ISSUE TITLE
@contextDump inside a fields file crash the app

### ISSUE THREAD

**Issue by MoutaiA** [nodea-software/nodea#28]
## Step to reproduce

- Inside an entity_fields.dust
- Put a <script>console.log({@contextDump /);</script>

Then refresh the page, the server will crash with the following error:

> [DUST:ERROR] Error in helper `contextDump`: Converting circular structure to JSON
    --> starting at object with constructor 'Socket'
    |     property 'parser' -> object with constructor 'HTTPParser'
    --- property 'socket' closes the circle

**Comment by MoutaiA** [comment]
By the way, it doesn't matter if we use a <scrip></script> or directly the helper, the same error occurs

**Comment by EoiFirst** [comment]
This would happen in any file since it depends on your json data and not where you try to log it.

You can't have an object referencing itself in your json tree. Logging it would end up in an infinite loop.

Your problem here is the data you're logging.

**Comment by Syno0** [comment]
As said @EoiFirst the problem does not come from the contextDump function it comes from the data you are trying to dump. In this case it is more of an error handling on the lindekin-dustjs module side. On the side of Nodea the good practice is to be vigilant about what you dump to avoid this problem.
