### ISSUE TITLE
Setting up roles and group cursor

### ISSUE THREAD

**Issue by slidebend** [nodea-software/nodea#3]
Hi,
I try to set up access rights in group and roles.
When I put my mouse over the rows displayed, my cursor is displayed like a one finger up pointer (like when you are over an hypertext link) but I cannot click and change any value. I need to navigate over the switch button to change values... 
The thing is, this switch button set mouse cursor back to normal! This should be reversed. It's totally confusing. 
Can you fix this ?

**Comment by Syno0** [comment]
Fix css in commit: https://github.com/nodea-software/nodea/commit/33d74b5219a62d948a055f5637554fa2a7aa5720

**Comment by slidebend** [comment]
Fixed
