### ISSUE TITLE
Refresh datatable filters does not empty filter values

### ISSUE THREAD

**Issue by newmips** [nodea-software/Nodea#30]
Hey,
In a generated application, when I click on the refresh button, the values inserted in headers of data table to filter it, remains present.
Can you fix this please ?
Thank you.

**Comment by newmips** [comment]
Hi,
I have fixed this issue in "_core/public/js/nodeaTable.js" :
```
{
                text: '<i class="fas fa-sync-alt"></i>',
                titleAttr: STR_LANGUAGE.reset_filter,
                action: (event, datatable, button, config) => {
                	var tableID = button.parent().siblings('table').attr('id');
                    localStorage.setItem("nodea_filter_save_" + tableID, null);
                    // TODO: reload only table
                    // location.reload();
                    $("thead.filters > tr > th > input").val('').trigger('change');
                    var table = button.parent().siblings('table').DataTable(); 
					table.search('').columns().search('').draw();
                }
},
 ```
However, it seems localstorage values are strangely stored with a # in key. Ex. "nodea_filter_save_#table_e_product"
So, I have also modified "initDataTable" and "saveFilterVal" call to save it properly in "nodea_filter_save_table_e_product" :
Line 656 
```
defaults.saveFilterVal(tableID.substring(1), columns[colIdx].data, value);
```

**Comment by FLafaye** [comment]
Link to commit:
https://github.com/nodea-software/Nodea/commit/afe60a6c5311924b01d72436b86681d974b8622b

Will be delivered in 3.1
