### ISSUE TITLE
Remove the history, status of a sub-entity.

### ISSUE THREAD

**Issue by MoutaiA** [nodea-software/Nodea#31]
The tab status' history should not be displayed in a sub-entity.

Step to reproduce:

- Create the main entity & create a has many relation
  * create entity MainEntity
  * create entity SubEntity
  * add component status
  * entity MainEntity has many SubEntity

- Create an instance of the main entity, and the subentity.

- Click on the show page of the subentity through the main (with the tab).

![main](https://user-images.githubusercontent.com/68805571/147737537-69095e35-e827-48db-8e0b-2df24615ff91.png)

1. Click on the History tab of the sub entity.

![historique](https://user-images.githubusercontent.com/68805571/147737535-4f59fe78-c7bf-4974-ba89-0be97bd507c1.png)

The screen become blank.

**Comment by FLafaye** [comment]
Workaround :
https://github.com/nodea-software/Nodea/commit/6abd501ec3b0a7a2378d3b01183d716d5eae547d
