### ISSUE TITLE
Promise.allSettled is not a function

### ISSUE THREAD

**Issue by newmips** [nodea-software/nodea#32]
Hi,
I have this issue in Nodea using tasks: Promise.allSettled is not a function
Issue refers to `_core/helpers/status.js` at line 66:
```
await Promise.allSettled(mediaExecutionPromises);
```

**Comment by newmips** [comment]
A way to solve it is either to upgrade to node 12.17.0 (as I am currently in 10.21.0)
or to set
```
await Promise.allSettled(mediaExecutionPromises);
```
in core files... which is not recommanded.
Can you fix this ?

**Comment by Syno0** [comment]
Nodea is with Node 14 or later as written in the README. Please upgrade your node version to fix this.
