### ISSUE TITLE
Display barcode issue

### ISSUE THREAD

**Issue by newmips** [nodea-software/nodea#35]
Hi,
Adding an entity with barcode field, does not display barcode on show page. Getting a javascript error like below:

TypeError: r.options(...)[n.format] is not a function

Script is:
create entity Product
add field MyBC with type barcode

It is certainly due to JsBarcode library or the way it is called.
Any idea ?
Thank you

**Comment by Syno0** [comment]
Indeed when creating a field with type barcode it will result by giving to JSBarcode library the "barcode" format which is not handle. 
To fix this please replace in your HTML input:
`data-custom-type="barcode"`
with
`data-custom-type="code128"`

Will be fixed in 3.1.

**Comment by Syno0** [comment]
Fixed in https://github.com/nodea-software/nodea/commit/afe60a6c5311924b01d72436b86681d974b8622b

Will be released with 3.1
