### ISSUE TITLE
Accumulation of error on inputs type mail or tel

### ISSUE THREAD

**Issue by MoutaiA** [nodea-software/Nodea#37]
Tested on 2 environments.

When you add some bad values for an input mail or tel, there is an accumulation of these errors.

![erreur_mail_tel](https://user-images.githubusercontent.com/68805571/187472384-698a1d1f-63b9-452e-b3d5-2c3f3907eeae.png)

**Comment by FLafaye** [comment]
Will be delivered in 3.1
