### ISSUE TITLE
Tabs with has many relationship go beyond screen

### ISSUE THREAD

**Issue by MoutaiA** [nodea-software/Nodea#38]
If your entity does have many tabs, as soon as you click on a tab with a has many relationship, all the other tabs resize.

On a has one:
![has_one](https://user-images.githubusercontent.com/68805571/188603524-3bc8e84f-4aac-4849-9927-e41d1bfd01a4.png)

On a has many:
![has_many](https://user-images.githubusercontent.com/68805571/188603620-ee16b53a-e152-4fb7-9e73-e673660f367c.png)

As you see, instead of wrapping to the next row, it goes of screens.

**Comment by FLafaye** [comment]
Problem not constat. 
AdminLTE has been updated in 3.1, see if fixes the problem.
