### ISSUE TITLE
Deploy error - toSyncProd.json file missing

### ISSUE THREAD

**Issue by slidebend** [nodea-software/nodea#4]
Hey,
When I execute instruction "deploy" in demo env, I have the following error:
```
 ENOENT: no such file or directory, stat '/app/services/../workspace/a_ocean-dive/models/toSyncProd.json'
```
Is it a limitation of demo env? If not, is it possible to fix it or can you provide a working solution?
Thank you.

**Comment by Syno0** [comment]
The deployment function is currently under development. It will be usable in a future version. However, it is indeed necessary to improve Nodea's response to warn the user of the current state of this instruction. This warning will be added in 3.0.1

**Comment by Syno0** [comment]
For 3.0.1 it will throw an error that the instruction is on maintenance
https://github.com/nodea-software/nodea/commit/51c92bdbcdbe69a214ba98803cc536301980814e

**Comment by Syno0** [comment]
Available on https://test.nodea.studio

**Comment by slidebend** [comment]
Fixed
