### ISSUE TITLE
Demo env - Create issue button not working

### ISSUE THREAD

**Issue by slidebend** [nodea-software/nodea#5]
Hi,
The button to declare issue in preview page is pointing on:
https://github.com/nodeasoftware/nodea/issues/new
It seems address should be with a dash:
https://github.com/nodea-software/nodea/issues/new

**Comment by slidebend** [comment]
Same on home page, repo link is not correct:
https://github.com/nodeasoftware
Should be :
https://github.com/nodea-software

**Comment by Syno0** [comment]
Everything is already fine, please check =>

https://github.com/nodea-software/nodea/blob/2c7be8e79a0e4ff0198f1ef23552c6880fd720e5/views/front/home.dust#L131

https://github.com/nodea-software/nodea/blob/2c7be8e79a0e4ff0198f1ef23552c6880fd720e5/views/front/preview/preview.dust#L114

**Comment by slidebend** [comment]
Fixed
