### ISSUE TITLE
delete module ModuleName doesnt work

### ISSUE THREAD

**Issue by Alex-Ljeune** [nodea-software/nodea#6]
Hi, I try to delete a module I just created with the command line "delete module référenciel" and it throw me this error : 

> ENOENT: no such file or directory, unlink '/app/workspacea_micromania/views/layout_m_referenciel.dust'

I tried both with or without the accents in the module name. 
However I success to select it with "select module référenciel".

Any idea of what happens ?

**Comment by Syno0** [comment]
https://github.com/nodea-software/nodea/commit/ff955b753ca5cb2137db009e1b22362b58571958

**Comment by Syno0** [comment]
Available on https://test.nodea.studio

**Comment by Alex-Ljeune** [comment]
It works fine ! Thank you
