### ISSUE TITLE
'Has many existing' association doesnt work well

### ISSUE THREAD

**Issue by Alex-Ljeune** [nodea-software/nodea#7]
Hi Nodea's team ! 

When I try to add a relation between a product and his genre it trows me an error

> Not Found The requested URL /add was not found on this server.

So, first I initiate the relation with `entity Produit has many existing Genres through field Titre called Genre(s)`
It gaves me a success with this screen : 

![Vue produit](https://user-images.githubusercontent.com/70142940/116989769-7ae6fc80-acd2-11eb-858b-db94d380795b.png)

Then I try to catch my genre on this screen

![Vue produit genres](https://user-images.githubusercontent.com/70142940/116989832-92be8080-acd2-11eb-990d-56b63cd926c0.png)

and it ends with 

![Vue_Not_Found](https://user-images.githubusercontent.com/70142940/116989861-9ce07f00-acd2-11eb-9230-34c95d72b3a5.png)

Couldn't find where it is from, any suggestion ?

**Comment by Syno0** [comment]
Linking concerned commit: https://github.com/nodea-software/nodea/commit/761d86913bf0caa8d2509c78918bdcdafa7e2e76

**Comment by Syno0** [comment]
@Alex-Ljeune Test available on https://test.nodea.studio

**Comment by Alex-Ljeune** [comment]
Runs perfectly, thank you
