### ISSUE TITLE
uniqueness on relational field is not permitted

### ISSUE THREAD

**Issue by Alex-Ljeune** [nodea-software/nodea#8]
Hello team,

I have a relational field set with "create field [Jeu] related to [Produit] using [Titre]" wich perfectly works but I would like to set it unique. When I pass "set field [Jeu] [unique]" In studio it throws the error : 

> (conn=438, no: 1072, SQLState: 42000) Key column 'f_jeu' doesn't exist in table sql: ALTER TABLE `np_a_gamesales`.`e_informations` ADD CONSTRAINT e_informations_f_jeu_unique UNIQUE (`f_jeu`); - parameters:[]

The command works on the other fields (without relation),
Can you see where is it from ?

**Comment by Syno0** [comment]
https://github.com/nodea-software/nodea/commit/d5d23a1f69a9a2be5f09cd68abae06b480824b32

**Comment by Syno0** [comment]
Available on https://test.nodea.studio

**Comment by Alex-Ljeune** [comment]
Runs fine, thank you
