### ISSUE TITLE
setting a field as required in entity User when importing a script makes the loading crash

### ISSUE THREAD

**Issue by Alex-Ljeune** [nodea-software/nodea#9]
Hello team,
I tried to set a new field in the entity User in my script and if I set it as required the application will not get imported correctly when charging the script.
It is an SQL error : 
![sqlerror](https://user-images.githubusercontent.com/70142940/117446611-99503080-af3c-11eb-97a2-0ae4fd58a7f0.png)
`Column 'f_nom' cannot be null`

which is quite logic because my user Admin as a field 'Name' null.

can we fix it ?

**Comment by Syno0** [comment]
Test available on: https://test.nodea.studio

**Comment by Alex-Ljeune** [comment]
Fixed ! Thanks !
